apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::421687806205:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-13266C5CBQW0D
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::421687806205:role/UdacityFlaskDeployCBKubectlRole
      username: build   
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-01T13:57:00Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1820"
  uid: 27e02011-8090-4f02-9843-ba4af94cc740
